## Context

Starting in 2008, every year Forbes Magazine publishes a list of America's best colleges. When it comes to the question everyone seems to be asking, “Is college worth it? this published list of colleges comes handy to take a decision based on student's requirement or desire.

The mission of the college ranking by Forbes Magazine is to conduct an annual review of the undergraduate institutions that deliver the top academics, best experiences, career success and lowest debt. Whether a school is in the Top 10 or near the bottom of the list, the 650 colleges are the best in the country.

For most families, choosing a four-year college is one of the biggest and most expensive decisions they can make. For students, this time of their life may layout their future plans. So choose carefully.

## About Data

The data set contains the rankings of 650 Unites States colleges along with various other statistics pertaining to each school.

<img src ="https://i.ibb.co/sKwQjfw/Stanford.jpg" width=80% height =40%></img>

### Load required packages

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import seaborn as sns

In [4]:
import matplotlib.pyplot as plt

### Load the data into pandas dataframe and view the details

In [5]:
df=pd.read_csv('AmericasTopColleges.csv')

In [6]:
df.head(5)

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu

### Dimension of the data

*'shape'* is a property associated with DataFrame. It returns a tuple representing the dimensionality of the DataFrame. First value is giving number of rows and second value is giving number of columns.

In [7]:
df.shape

(650, 17)

### Datatype of the fields in the data

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rank                      650 non-null    int64
 1   Name                      650 non-null    object
 2   City                      650 non-null    object
 3   State                     650 non-null    object
 4   Public/Private            650 non-null    object
 5   Undergraduate Population  650 non-null    int64
 6   Student Population        650 non-null    int64
 7   Net Price                 648 non-null    float64
 8   Average Grant Aid         646 non-null    float64
 9   Total Annual Cost         650 non-null    int64
 10  Alumni Salary             635 non-null    float64
 11  Acceptance Rate           648 non-null    float64
 12  SAT Lower                 551 non-null    float64
 13  SAT Upper                 551 non-null    float64
 14  ACT Lower                 553 non-null    float64
 15  ACT Upper                 553 non-null    float64
 16  Website                   645 non-null    object
dtypes: float64(8), int64(4), object(5)
memory usage: 86.5+ KB

In [9]:
df.describe()

,Rank,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
count,650.00000,650.000000,650.000000,648.000000,646.000000,650.000000,635.000000,648.000000,551.000000,551.000000,553.000000,553.000000
mean,325.50000,10002.692308,12022.290769,22336.947531,20031.208978,50330.175385,98851.968504,61.597222,1110.145191,1308.078040,23.278481,28.441230
std,187.78312,11162.172430,13175.091581,8269.912032,11175.869976,13223.055038,14335.249458,22.024781,127.744079,113.553237,3.729318,3.058115
min,1.00000,185.000000,386.000000,0.000000,2975.000000,0.000000,70700.000000,5.000000,820.000000,1060.000000,15.000000,20.000000
25%,163.25000,2020.250000,2240.750000,16410.000000,9288.250000,39917.000000,88600.000000,48.000000,1020.000000,1230.000000,21.000000,26.000000
50%,325.50000,4503.000000,6269.000000,21989.000000,19605.000000,50265.000000,96400.000000,67.000000,1080.000000,1290.000000,22.000000,28.000000
75%,487.75000,15657.000000,17788.000000,27580.500000,27474.500000,60771.750000,105600.000000,78.000000,1180.000000,1380.000000,25.000000,31.000000
max,650.00000,65100.000000,75044.000000,47270.000000,50897.000000,75735.000000,158200.000000,100.000000,1530.000000,1590.000000,34.000000,35.000000

### Check the missing values in the data
'isnull()' method detects missing values. It returns a boolean same-sized object indicating if the values are NA. NA values, gets mapped to True values.Everything else gets mapped to False values.

'sum()' method followed by 'isnull()' adds up all the True instances per column to give a summary of missing values per column

In [10]:
df.isnull()

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
646,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
647,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
648,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,False
649,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

Rank                         0
Name                         0
City                         0
State                        0
Public/Private               0
Undergraduate Population     0
Student Population           0
Net Price                    2
Average Grant Aid            4
Total Annual Cost            0
Alumni Salary               15
Acceptance Rate              2
SAT Lower                   99
SAT Upper                   99
ACT Lower                   97
ACT Upper                   97
Website                      5
dtype: int64

See the column names , with space

### Data Cleanup

Let's first drop all columns that are not need.

In [14]:
df.drop(columns=['Website'],inplace=True)

In [15]:
df.head()

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rank                      650 non-null    int64
 1   Name                      650 non-null    object
 2   City                      650 non-null    object
 3   State                     650 non-null    object
 4   Public/Private            650 non-null    object
 5   Undergraduate Population  650 non-null    int64
 6   Student Population        650 non-null    int64
 7   Net Price                 648 non-null    float64
 8   Average Grant Aid         646 non-null    float64
 9   Total Annual Cost         650 non-null    int64
 10  Alumni Salary             635 non-null    float64
 11  Acceptance Rate           648 non-null    float64
 12  SAT Lower                 551 non-null    float64
 13  SAT Upper                 551 non-null    float64
 14  ACT Lower                 553 non-null    float64
 15  ACT Upper                 553 non-null    float64
dtypes: float64(8), int64(4), object(4)
memory usage: 81.4+ KB

### Reset the index of the dataframe

In [17]:
df.reset_index(inplace=True)

### Check the first 5 rows of the dataset

In [18]:
df.head(5)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0
1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0
2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0
3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0
4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0

### Display the last five rows of the dataset

In [20]:
df.tail(5)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
645,645,646,New Mexico State University,Las Cruces,NM,Public,13379,14432,8625.0,9582.0,34720,96700.0,64.0,910.0,1160.0,18.0,23.0
646,646,647,Indiana State University,Terre Haute,IN,Public,13626,13763,13012.0,9297.0,32938,85600.0,85.0,900.0,1110.0,17.0,23.0
647,647,648,Emory &amp; Henry College,Emory,VA,Private,1094,1226,19340.0,27155.0,48100,70700.0,72.0,988.0,1170.0,19.0,25.0
648,648,649,Wells College,Aurora,NY,Private,488,516,22828.0,30207.0,55180,NaN,80.0,NaN,NaN,NaN,NaN
649,649,650,Catawba College,Salisbury,NC,Private,1336,1463,19807.0,23662.0,44921,78100.0,42.0,930.0,1100.0,18.0,23.0

### Recheck the dimension and info of the data

In [21]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     650 non-null    int64
 1   Rank                      650 non-null    int64
 2   Name                      650 non-null    object
 3   City                      650 non-null    object
 4   State                     650 non-null    object
 5   Public/Private            650 non-null    object
 6   Undergraduate Population  650 non-null    int64
 7   Student Population        650 non-null    int64
 8   Net Price                 648 non-null    float64
 9   Average Grant Aid         646 non-null    float64
 10  Total Annual Cost         650 non-null    int64
 11  Alumni Salary             635 non-null    float64
 12  Acceptance Rate           648 non-null    float64
 13  SAT Lower                 551 non-null    float64
 14  SAT Upper                 551 non-null    float64
 15  ACT Lower                 553 non-null    float64
 16  ACT Upper                 553 non-null    float64
dtypes: float64(8), int64(5), object(4)
memory usage: 86.5+ KB

In [22]:
df.shape

(650, 17)

# Data Analysis

### Get Summary of Data

In [23]:
df.describe()

,index,Rank,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper
count,650.00000,650.00000,650.000000,650.000000,648.000000,646.000000,650.000000,635.000000,648.000000,551.000000,551.000000,553.000000,553.000000
mean,324.50000,325.50000,10002.692308,12022.290769,22336.947531,20031.208978,50330.175385,98851.968504,61.597222,1110.145191,1308.078040,23.278481,28.441230
std,187.78312,187.78312,11162.172430,13175.091581,8269.912032,11175.869976,13223.055038,14335.249458,22.024781,127.744079,113.553237,3.729318,3.058115
min,0.00000,1.00000,185.000000,386.000000,0.000000,2975.000000,0.000000,70700.000000,5.000000,820.000000,1060.000000,15.000000,20.000000
25%,162.25000,163.25000,2020.250000,2240.750000,16410.000000,9288.250000,39917.000000,88600.000000,48.000000,1020.000000,1230.000000,21.000000,26.000000
50%,324.50000,325.50000,4503.000000,6269.000000,21989.000000,19605.000000,50265.000000,96400.000000,67.000000,1080.000000,1290.000000,22.000000,28.000000
75%,486.75000,487.75000,15657.000000,17788.000000,27580.500000,27474.500000,60771.750000,105600.000000,78.000000,1180.000000,1380.000000,25.000000,31.000000
max,649.00000,650.00000,65100.000000,75044.000000,47270.000000,50897.000000,75735.000000,158200.000000,100.000000,1530.000000,1590.000000,34.000000,35.000000

# Sliciing of Data

### 1) Which are the top 5 colleges listed in the Forbes Magazine 2019?

In [24]:
print(df['Name'].head())

0                       Harvard University
1                      Stanford University
2                          Yale University
3    Massachusetts Institute of Technology
4                     Princeton University
Name: Name, dtype: object

We can also save the information in an object 'top5' and display it

In [25]:
top5=df.head()

print(top5)

   index  Rank                                   Name       City State  \
0      0     1                     Harvard University  Cambridge    MA
1      1     2                    Stanford University   Stanford    CA
2      2     3                        Yale University  New Haven    CT
3      3     4  Massachusetts Institute of Technology  Cambridge    MA
4      4     5                   Princeton University  Princeton    NJ

  Public/Private  Undergraduate Population  Student Population  Net Price  \
0        Private                     13844               31120    14327.0
1        Private                      8402               17534    13261.0
2        Private                      6483               12974    18627.0
3        Private                      4680               11466    20771.0
4        Private                      5659                8273     9327.0

   Average Grant Aid  Total Annual Cost  Alumni Salary  Acceptance Rate  \
0            49870.0              69600       146800.0              5.0
1            50134.0              69109       145200.0              5.0
2            50897.0              71290       138300.0              7.0
3            43248.0              67430       155200.0              7.0
4            48088.0              66150       139400.0              6.0

   SAT Lower  SAT Upper  ACT Lower  ACT Upper
0     1460.0     1590.0       32.0       35.0
1     1390.0     1540.0       32.0       35.0
2     1460.0     1580.0       32.0       35.0
3     1490.0     1570.0       33.0       35.0
4     1430.0     1570.0       31.0       35.0

### 2) Which state and city do the top 5 colleges belong to?

In [29]:
print(df[['State','City']].head())

  State       City
0    MA  Cambridge
1    CA   Stanford
2    CT  New Haven
3    MA  Cambridge
4    NJ  Princeton

### 3) How many states and which all states have the colleges listed by Forbes?

In [34]:
len(df['State'].unique())

51

In [35]:
df['State'].unique()

array(['MA', 'CA', 'CT', 'NJ', 'PA', 'RI', 'NC', 'NH', 'NY', 'DC', 'IL',
       'IN', 'MI', 'TX', 'MD', 'ME', 'TN', 'MO', 'VA', 'VT', 'CO', 'MN',
       'GA', 'WA', 'WI', 'FL', 'OH', 'IA', 'UT', 'OR', 'LA', 'SC', 'DE',
       'AL', 'AZ', 'OK', 'NE', 'KY', 'KS', 'AR', 'WY', 'NV', 'MS', 'ND',
       'HI', 'MT', 'SD', 'NM', 'ID', 'WV', 'AK'], dtype=object)

### 4) In all how many private and public colleges are there in the given list?

In [36]:
df['Public/Private'].value_counts()

Public/Private
Private    400
Public     250
Name: count, dtype: int64

### 5) From the list how many colleges are there within each State? Which State has highest number of colleges?

In [41]:

state_counts = df['State'].value_counts()

hs = state_counts.idxmax()
hc = state_counts.max()

print(f"Highest state: {hs}")
print(f"Highest count: {hc}")

Highest state: NY
Highest count: 68

### 6) What is percentage of undergraduates in each college? (Add a new field to calculate)

In [43]:



df['Percentage UG'] = round((df['Undergraduate Population'] / df['Student Population']) * 100, 2)

df.head(5)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG
0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,44.49
1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,47.92
2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,49.97
3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,40.82
4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,68.40

### 7) Which are the 5 colleges with highest percentage of undergraduates?

In [46]:

top_5_ug = df.sort_values(by='Percentage UG', ascending=False).head(5)

top_5_ug

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG
570,570,571,"University of Texas, Rio Grande Valley",Edinburg,TX,Public,27807,27809,3901.0,9398.0,29995,81200.0,80.0,950.0,1120.0,17.0,22.0,99.99
253,253,254,Saint John's University (MN),Collegeville,MN,Private,1815,1816,23977.0,27780.0,55872,108400.0,80.0,970.0,1190.0,22.0,27.0,99.94
565,565,566,Oakland University,Rochester,MI,Public,19321,19333,12779.0,9476.0,36581,93300.0,84.0,1010.0,1230.0,21.0,27.0,99.94
364,364,365,Salisbury University,Salisbury,MD,Public,8714,8721,18792.0,5527.0,34102,89800.0,65.0,NaN,NaN,NaN,NaN,99.92
345,345,346,St. Norbert College,De Pere,WI,Private,2162,2165,24930.0,20123.0,48110,88700.0,79.0,1110.0,1230.0,22.0,27.0,99.86

### 8) 5 colleges that receive highest Average Grant Aid?

In [48]:
top_5_aid = df.sort_values(by='Average Grant Aid', ascending=False).head(5)

top_5_aid

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG
2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,49.97
1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,47.92
0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,44.49
27,27,28,Amherst College,Amherst,MA,Private,1836,1945,22463.0,49467.0,71300,116500.0,13.0,1400.0,1560.0,32.0,34.0,94.40
13,13,14,Columbia University,New York,NY,Private,8523,30454,24231.0,49185.0,74199,126800.0,7.0,1410.0,1570.0,31.0,34.0,27.99


### 9) What is the average Undergraduate population in State of 'CA'?

In [ ]:
ca_colleges = df[df['State'] == 'CA']

ca_ug_average = ca_colleges['Undergraduate Population'].mean()

ca_ug_average

np.float64(13186.910714285714)

### 10) Which are the colleges where chances of admission is high?

In [50]:
high_admission_colleges = df.sort_values(by='Acceptance Rate', ascending=False).head(5)

high_admission_colleges

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG
605,605,606,"University of Texas, El Paso",El Paso,TX,Public,24386,25078,8135.0,9183.0,36955,92100.0,100.0,920.0,1130.0,16.0,22.0,97.24
626,626,627,University of Southern Mississippi,Hattiesburg,MS,Public,13606,14478,13178.0,9292.0,24883,83900.0,98.0,NaN,NaN,19.0,26.0,93.98
637,637,638,Wright State University,Dayton,OH,Public,14332,15957,16249.0,6546.0,32506,87800.0,97.0,980.0,1270.0,19.0,25.0,89.82
636,636,637,Marlboro College,Marlboro,VT,Private,185,390,17636.0,33054.0,55625,NaN,97.0,NaN,NaN,NaN,NaN,47.44
346,346,347,University of Wyoming,Laramie,WY,Public,10874,12397,13070.0,7422.0,31387,98800.0,97.0,1040.0,1290.0,22.0,27.0,87.71

### 11) Find if there are any 'Art' colleges in the list

To find a specific string value 'Art' we will use the 'contains()' method. We will pass the string in the paranthesis which needs to be located in the dataframe variable.

In [51]:
art_colleges = df[df['Name'].str.contains('Art', na=False)]

art_colleges.head(5)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG
302,302,303,Maryland Institute College of Art,Baltimore,MD,Private,2041,2128,38763.0,18939.0,62850,84500.0,62.0,1060.0,1290.0,24.0,29.0,95.91
401,401,402,California Institute of the Arts,Santa Clarita,CA,Private,991,1498,46101.0,15401.0,68993,91000.0,24.0,NaN,NaN,NaN,NaN,66.15

### 12) Lets divide the Alumni Salary equally into 3 buckets (Low Salary - L; Medium Salary - M; High Salary - H ) and check which colleges falls in 'H' bucket

In [52]:

df_cleaned = df.dropna(subset=['Alumni Salary']).copy()
df_cleaned['Salary Bucket'] = pd.qcut(df_cleaned['Alumni Salary'], q=3, labels=['L', 'M', 'H'])

high_salary_colleges = df_cleaned[df_cleaned['Salary Bucket'] == 'H']

high_salary_colleges.head(5)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG,Salary Bucket
0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,44.49,H
1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,47.92,H
2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,49.97,H
3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,40.82,H
4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,68.40,H

Take a copy of the original DataFrame to work on

In [53]:
df_work = df.copy()

df_work['Salary Bucket'] = pd.qcut(df_work['Alumni Salary'], q=3, labels=['L', 'M', 'H'])

In [54]:
df_work.head(5)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG,Salary Bucket
0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,44.49,H
1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,47.92,H
2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,49.97,H
3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,40.82,H
4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,68.40,H

'cut()' function bins values into discrete intervals. 'cut()' function is used when you need to segment and sort data values into bins. This function is also useful for going from a continuous variable to a categorical variable.

In the above code we have created 3 bins using 'Alumni Salary' column. Lowest range of salary is labelled as 'L', middle range is labelled as 'M' and highest range of salary is labelled as 'H'. These labels are saved in a new column 'Alumni Sal Level'.

Note: The entire range of the 'Alumni Salary' has been divided into 3 equal ranges i.e. 3 bins

### 13) Let's check the mean Alumni Salary at each level

In [56]:
df_work = df_work.dropna(subset=['Alumni Salary'])
df_work['Alumni Sal Level'] = pd.cut(df_work['Alumni Salary'], bins=3, labels=['L', 'M', 'H'])

mean_salaries = df_work.groupby('Alumni Sal Level')['Alumni Salary'].mean()


print(mean_salaries)

Alumni Sal Level
L     89881.088083
M    109127.981651
H    138290.322581
Name: Alumni Salary, dtype: float64

C:\Users\jeeva\AppData\Local\Temp\ipykernel_21552\2273710867.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_salaries = df_work.groupby('Alumni Sal Level')['Alumni Salary'].mean()

### 14) Let's create a new dataframe to further analyze the 28 colleges with High Alumni Salary

In [57]:
high_salary_colleges.head(28)

,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Percentage UG,Salary Bucket
0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,44.49,H
1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,47.92,H
2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,49.97,H
3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,40.82,H
4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,68.40,H
5,5,6,University of Pennsylvania,Philadelphia,PA,Private,13437,25367,24242.0,44801.0,71715,133900.0,9.0,1420.0,1560.0,32.0,35.0,52.97,H
6,6,7,Brown University,Providence,RI,Private,7390,10095,30205.0,42455.0,71050,127600.0,8.0,1405.0,1570.0,31.0,35.0,73.20,H
7,7,8,California Institute of Technology,Pasadena,CA,Private,1002,2238,24245.0,41408.0,68901,151600.0,8.0,1530.0,1590.0,34.0,35.0,44.77,H
8,8,9,Duke University,Durham,NC,Private,7184,16130,35737.0,47836.0,71764,132100.0,10.0,1380.0,1540.0,31.0,35.0,44.54,H
9,9,10,Dartmouth College,Hanover,NH,Private,4693,6509,30421.0,47171.0,71827,130900.0,10.0,1430.0,1560.0,30.0,34.0,72.10,H
10,10,11,Cornell University,Ithaca,NY,Private,14774,23016,31230.0,36164.0,70321,128200.0,13.0,1390.0,1550.0,31.0,34.0,64.19,H
11,11,12,Pomona College,Claremont,CA,Private,1599,1665,15840.0,48930.0,69725,117200.0,8.0,1370.0,1530.0,30.0,34.0,96.04,H
12,12,13,"University of California, Berkeley",Berkeley,CA,Public,31133,41891,15859.0,18319.0,65003,131800.0,17.0,1260.0,1480.0,30.0,34.0,74.32,H
13,13,14,Columbia University,New York,NY,Private,8523,30454,24231.0,49185.0,74199,126800.0,7.0,1410.0,1570.0,31.0,34.0,27.99,H
14,14,15,Georgetown University,Washington,DC,Private,8194,19005,30107.0,41893.0,71580,122200.0,16.0,1350.0,1520.0,30.0,34.0,43.11,H
15,15,16,University of Chicago,Chicago,IL,Private,6915,16227,25455.0,37883.0,75735,114200.0,9.0,1480.0,1580.0,32.0,35.0,42.61,H
16,16,17,Northwestern University,Evanston,IL,Private,10163,22008,24047.0,44247.0,72980,115400.0,9.0,1420.0,1560.0,32.0,34.0,46.18,H
17,17,18,University of Notre Dame,Notre Dame,IN,Private,8664,12467,28768.0,39590.0,69395,130500.0,19.0,1370.0,1520.0,32.0,34.0,69.50,H
18,18,19,Williams College,Williamstown,MA,Private,2134,2227,22667.0,48050.0,70650,127500.0,15.0,1400.0,1570.0,31.0,35.0,95.82,H
19,19,20,"University of Michigan, Ann Arbor",Ann Arbor,MI,Public,29773,46002,14860.0,18751.0,62176,112200.0,27.0,1330.0,1500.0,30.0,33.0,64.72,H
20,20,21,Rice University,Houston,TX,Private,4036,7022,20237.0,36387.0,63158,129500.0,16.0,1490.0,1580.0,33.0,35.0,57.48,H
21,21,22,Johns Hopkins University,Baltimore,MD,Private,7825,25151,33586.0,38542.0,69863,117100.0,13.0,1450.0,1570.0,33.0,35.0,31.11,H
22,22,23,Harvey Mudd College,Claremont,CA,Private,847,861,34464.0,33782.0,74428,158200.0,15.0,1470.0,1570.0,33.0,35.0,98.37,H
23,23,24,United States Naval Academy,Annapolis,MD,Public,4495,4526,0.0,NaN,0,152800.0,8.0,1150.0,1370.0,NaN,NaN,99.32,H
24,24,25,Swarthmore College,Swarthmore,PA,Private,1577,1630,20511.0,46105.0,68846,123200.0,11.0,1380.0,1540.0,31.0,34.0,96.75,H
25,25,26,Bowdoin College,Brunswick,ME,Private,1816,1965,22810.0,41143.0,68070,112000.0,14.0,NaN,NaN,NaN,NaN,92.42,H
26,26,27,Vanderbilt University,Nashville,TN,Private,7006,12592,19959.0,41359.0,67392,119100.0,11.0,1440.0,1570.0,32.0,35.0,55.64,H
27,27,28,Amherst College,Amherst,MA,Private,1836,1945,22463.0,49467.0,71300,116500.0,13.0,1400.0,1560.0,32.0,34.0,94.40,H

Passing 'include = 'all'' to describe() method provides descriptive summary of all fields in the DataFrame. 'T' property transposes the table which helps in reviewing the statistics per column

In [58]:
high_salary_colleges.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
index,211.0,NaN,NaN,NaN,155.341232,124.997513,0.0,54.5,124.0,232.5,575.0
Rank,211.0,NaN,NaN,NaN,156.341232,124.997513,1.0,55.5,125.0,233.5,576.0
Name,211,211,Harvard University,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,211,169,New York,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,211,38,NY,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Public/Private,211,2,Private,139,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Undergraduate Population,211.0,NaN,NaN,NaN,10922.616114,11405.954641,847.0,2580.0,5777.0,17813.5,53515.0
Student Population,211.0,NaN,NaN,NaN,14395.099526,14300.914421,861.0,2955.0,8273.0,22892.5,67929.0
Net Price,211.0,NaN,NaN,NaN,24926.483412,8895.56498,0.0,18395.5,24814.0,32182.0,43969.0
Average Grant Aid,207.0,NaN,NaN,NaN,25103.038647,12894.76491,3597.0,13180.5,25110.0,35595.5,50897.0
Total Annual Cost,211.0,NaN,NaN,NaN,57650.236967,14377.179875,0.0,50230.0,62203.0,68813.5,75735.0
Alumni Salary,211.0,NaN,NaN,NaN,114876.777251,11864.247254,102300.0,105700.0,111200.0,118800.0,158200.0
Acceptance Rate,211.0,NaN,NaN,NaN,46.734597,24.634774,5.0,24.0,48.0,68.5,92.0
SAT Lower,188.0,NaN,NaN,NaN,1217.281915,126.422982,950.0,1130.0,1195.0,1310.0,1530.0
SAT Upper,188.0,NaN,NaN,NaN,1401.239362,105.146657,1170.0,1330.0,1390.0,1492.5,1590.0
ACT Lower,185.0,NaN,NaN,NaN,26.502703,3.616274,19.0,24.0,26.0,30.0,34.0
ACT Upper,185.0,NaN,NaN,NaN,30.978378,2.62504,25.0,29.0,31.0,33.0,35.0
Percentage UG,211.0,NaN,NaN,NaN,79.620521,16.723457,27.99,70.5,82.62,93.575,99.94
Salary Bucket,211,1,H,211,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Happy Learning!!!